@extends('main_master') 
	@section('main_content')    
	@if($flag == 1)
  		@include('UI.components/user/user_profile')  
  	@elseif($flag == 2) 
  		@include('UI.components/user/user_order')  
  	@elseif($flag == 3) 
  		@include('UI.components/user/user_booking')  
  	@elseif($flag == 4) 
  		@include('UI.components/user/user_address')  
    @elseif($flag == 5) 
      @include('UI.components/user/user_change_password') 
    @elseif($flag == 6) 
      @include('UI.components/user/user_dashboard') 
    @elseif($flag == 7) 
      @include('UI.components/user/user_address_edit') 
    @elseif($flag == 8) 
      @include('UI.components/user/user_order_detail') 
  	@elseif($flag == 11) 
      @include('UI.components/user/user_wallet_history')
  	@elseif($flag == 9) 
	  @include('UI.components/user/user_booking_detail') 
	@elseif($flag == 10) 
  		@include('UI.components/user/change_password')
	@elseif($flag == 22) 
		 @include('UI.components/user/user_notification')
	@elseif($flag == 23) 
		 @include('UI.components/user/user_order_traking')
	@elseif($flag == 24) 
		 @include('UI.components/user/giftcardlist')
	@elseif($flag == 25) 
		 @include('UI.components/user/giftcardsend')
  	@endif
@stop 
